apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

images:
- name: harbor.bareflux.co/vibe-coding/vibe-coding-platform
  newTag: latest   # ArgoCD can override this with digest/tag
