apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

images:
- name: ghcr.io/sumansaurabh/task-bb/backend
  newTag: latest  # This will be overridden by ArgoCD