apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: harbor-timeout
  namespace: default
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
    customResponseHeaders:
      X-Frame-Options: "SAMEORIGIN"
      X-Content-Type-Options: "nosniff"
  buffering:
    maxRequestBodyBytes: 0
  retry:
    attempts: 3
    initialInterval: "100ms"
