apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sumansaurabh/task-bb.git  # Replace with your repo URL
    targetRevision: main
    path: k8s-manifests/app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    # NO automated section - API-controlled only!
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10
