apiVersion: v1
kind: ServiceAccount
metadata:
  name: lro-service-account
  namespace: default  # Change this to your actual namespace

---
# Update the existing Role to include pod-patcher permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-manager
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "patch", "update"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]

---
# The RoleBinding already exists and is correct
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nodejs-service-account-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: nodejs-service-account
  namespace: default
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: rbac.authorization.k8s.io
